### ISSUE TITLE
AtCoderコンテストURLの正規表現修正

### ISSUE THREAD

**Issue by nebocco** [qryxip/snowchains#142]
https://github.com/qryxip/cargo-compete/issues/177

https://github.com/qryxip/snowchains/blob/9ddc57b6114a3ff752769e4b4e87a157bb12ef8d/snowchains_core/src/web/atcoder.rs#L543

`A-z` にするだけで解決しそうですが、意図しないものにヒットしたりしてしまうのでしょうか？

**Comment by qryxip** [comment]
そうですね。大文字を考慮し忘れていました。直します。

**Comment by nebocco** [comment]
失礼いたしました。対応までしていただきありがとうございます。
