### ISSUE TITLE
Fails on downloading ARC133-A

### ISSUE THREAD

**Issue by nebocco** [qryxip/snowchains#148]
# 状況
```
% cargo run -- download -s atcoder -c arc133 -p a
   Compiling snowchains_core v0.13.1 (/home/user/snowchains/snowchains_core)
   Compiling snowchains v0.7.0 (/home/user/snowchains)
    Finished dev [unoptimized + debuginfo] target(s) in 32.47s
     Running `target/debug/snowchains download -s atcoder -c arc133 -p a`
GET https://atcoder.jp/contests/arc133/tasks ... 200 OK
GET https://atcoder.jp/contests/arc133/tasks_print ... 200 OK
warning: A: Could not extract the sample cases
A: Saved to /home/user/.snowchains/tests/atcoder/arc133/a.yml (no test cases)
```

# 原因
`try_extract_samples()` 内の以下の部分です。
https://github.com/qryxip/snowchains/blob/160ea1c24555dfef520f89aaa17c3d75f2823b7e/snowchains_core/src/web/atcoder.rs#L1752-L1762
https://github.com/qryxip/snowchains/blob/160ea1c24555dfef520f89aaa17c3d75f2823b7e/snowchains_core/src/web/atcoder.rs#L1800-L1806

この時、`samples` の中身は以下のようになっています。
```
[("5\n2 4 4 1 2\n", "2 1 2\n"), ("3\n1 1 1\n", " \n"), ("5\n1 1 2 3 3\n", "1 1 2\n")]
```
出力 2 が空白文字で始まっているため、invalid な文字列として認識されます。

問題として正しい出力は空文字列なのですが、実際にページの該当箇所を空文字列としてしまうと表示がダサくなってしまうので、便宜上入れているんだと思います。

空文字列なし：
![空文字列なし](https://user-images.githubusercontent.com/73807432/150937284-ed2c5f44-9502-4ba4-b323-4c4fc796728f.png)

空文字列あり：
![空文字列あり](https://user-images.githubusercontent.com/73807432/150937336-a4f8e6df-75d1-4b2d-859a-6a38dc539158.png)

# 解決案
文字列が `" \n"` だった場合は `""` に差し替えれば解決します （[典型90 - 002](https://atcoder.jp/contests/typical90/tasks/typical90_b) のサンプルには空白文字のない空文字列のケースがあり、こちらはパースに成功しています）。しかしこれによってホームページ上の誤った箇所を valid とみなして取り込んでしまう恐れがあります。`is_valid_text()` があるということは過去にそういうことがあったんだろうと想像しているのですが、具体的に懸念されるケースはあるでしょうか？

**Comment by qryxip** [comment]
`is_valid_text`を書いたときをあまり覚えていないのですが、単に`" \n"`を考慮し忘れただけだと思います。

ちなみにojはどうだったけと思い調べたのですが、[`lstrip`して](https://github.com/online-judge-tools/api-client/blob/v10.10.0/onlinejudge/service/atcoder.py#L697)から[`'\n'`を付けて](https://github.com/online-judge-tools/api-client/blob/v10.10.0/onlinejudge/_implementation/utils.py#L137-L138)いるため影響を受けていませんでした。

```console
❯ oj-api get-problem https://atcoder.jp/contests/arc133/tasks/arc133_a 2>/dev/null | jq '.result.tests[1].output'
"\n"
❯ oj-api get-problem https://atcoder.jp/contests/typical90/tasks/typical90_b 2>/dev/null | jq '.result.tests[1].output'
"\n"
```
